package com.revolut.assesment.project.constants;

public interface ApplicationConstants {
    enum AccountType {
        SAVINGS,
        CHECKING,
        CREDIT
    }

    String CREATE_USER_TABLE_QUERY = "CREATE TABLE IF NOT EXISTS USER (ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50), GENDER VARCHAR(10), EMAIL VARCHAR(100), PHONE_NUMBER VARCHAR(50), DOB TIMESTAMP, TIME_CREATED TIMESTAMP)";
    String CREATE_ACCOUNT_TABLE_QUERY = "";
    String CREATE_TRANSACTION_TABLE_QUERY = "";

    String GET_ALL_USERS_QUERY = "SELECT ID, FIRST_NAME, LAST_NAME, GENDER, EMAIL, PHONE_NUMBER, DOB, TIME_CREATED FROM USER";


    String INSERT_INTO_USER_QUERY = "INSERT INTO USER(FIRST_NAME, LAST_NAME, GENDER, EMAIL, PHONE_NUMBER, DOB, TIME_CREATED) values(?, ?, ?, ?, ?, ?, ?)";
}
