package com.revolut.assesment.project.constants;

public interface ApplicationConstants {
    enum AccountType {
        SAVINGS,
        CHECKING,
        CREDIT
    }


    String RESPONSE_ERROR_DATABAS_ISSUE = "Error accessing database!";
    String RESPONSE_ERROR_RECORD_NOT_CREATED = "Record Creation Failed!";
    String RESPONSE_ERROR_UNABLE_TO_FIND_USER = "Unable to find single User with given data!";

    String CREATE_USER_TABLE_QUERY = "CREATE TABLE IF NOT EXISTS USER (ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRSTNAME VARCHAR(50), LASTNAME VARCHAR(50), GENDER VARCHAR(10), EMAIL VARCHAR(100), PHONENUMBER VARCHAR(50), CITY VARCHAR(50), DOB VARCHAR(50))";
    String CREATE_ACCOUNT_TABLE_QUERY = "";
    String CREATE_TRANSACTION_TABLE_QUERY = "";

    String GET_ALL_USERS_QUERY = "SELECT ID, FIRSTNAME, LASTNAME, GENDER, EMAIL, PHONENUMBER, CITY, DOB FROM USER";


    String INSERT_INTO_USER_QUERY = "INSERT INTO USER(FIRSTNAME, LASTNAME, GENDER, EMAIL, PHONENUMBER, CITY, DOB) values(?, ?, ?, ?, ?, ?, ?)";
}
